# Generated by Django 4.2.7 on 2025-03-04 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('BranchCode', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('Company', models.CharField(max_length=50)),
                ('Location', models.CharField(max_length=50)),
                ('Employees', models.CharField(max_length=10)),
                ('BranchImage', models.ImageField(blank=True, null=True, upload_to='branch_image/')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('ApplicationCode', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('DateApplied', models.DateField(default=None, null=True)),
                ('YearsofExp', models.CharField(default='N/D', max_length=20)),
                ('ExpectSalary', models.CharField(default='N/D', max_length=20)),
                ('ApplicationStatus', models.CharField(default='N/D', max_length=50)),
                ('Remarks', models.CharField(default='N/D', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobList',
            fields=[
                ('JobCode', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('JobDate', models.DateField(default=None, null=True)),
                ('JobTitle', models.CharField(blank=True, default='N/D', max_length=50, null=True)),
                ('JobLoc', models.CharField(blank=True, default='N/D', max_length=100, null=True)),
                ('JobRole', models.CharField(blank=True, default='N/D', max_length=100, null=True)),
                ('JobBranch', models.CharField(blank=True, default='N/D', max_length=50, null=True)),
                ('JobDesc', models.CharField(blank=True, default='N/D', max_length=120, null=True)),
                ('JobBenefits', models.JSONField()),
                ('JobQual', models.JSONField()),
                ('JobTypes', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='UserAcc',
            fields=[
                ('UserCode', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('UserFullname', models.CharField(default='N/D', max_length=100)),
                ('Username', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=128)),
                ('ContactNum', models.CharField(max_length=11)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('AccDate', models.DateField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RejectedApplication',
            fields=[
                ('RejectedCode', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('RejectedDAte', models.DateField(default=None, null=True)),
                ('ApplicationStage', models.CharField(blank=True, default='N/D', max_length=50, null=True)),
                ('Remarks', models.CharField(blank=True, default='N/D', max_length=100, null=True)),
                ('ApplicationCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HromApp.jobapplication')),
            ],
        ),
        migrations.CreateModel(
            name='PendingApplication',
            fields=[
                ('PendingCode', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('ApplicationSched', models.DateField(default=None, null=True)),
                ('SchedBy', models.CharField(blank=True, default='N/D', max_length=10, null=True)),
                ('PendingStatus', models.CharField(blank=True, default='N/D', max_length=100, null=True)),
                ('Remarks', models.CharField(blank=True, default='N/D', max_length=100, null=True)),
                ('ApplicationCode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HromApp.jobapplication')),
            ],
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='ApplicantCode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HromApp.useracc'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='JobCode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HromApp.joblist'),
        ),
        migrations.CreateModel(
            name='InProgressApplication',
            fields=[
                ('InProgCode', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('AssesmentDAte', models.DateField(default=None, null=True)),
                ('AssesmentStatus', models.CharField(default='N/D', max_length=20)),
                ('InitInterview', models.BooleanField(default=False)),
                ('Exams', models.BooleanField(default=False)),
                ('CiBi', models.BooleanField(default=False)),
                ('FinalInterview', models.BooleanField(default=False)),
                ('ApplicationCode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HromApp.jobapplication')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmpCode', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('IdNo', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('Firstname', models.CharField(max_length=20)),
                ('Middlename', models.CharField(max_length=20)),
                ('Lastname', models.CharField(max_length=20)),
                ('Suffix', models.CharField(default=None, max_length=5, null=True)),
                ('DateofBirth', models.DateField(default=None, null=True)),
                ('BirthPlace', models.CharField(default=None, max_length=50, null=True)),
                ('Age', models.CharField(default=None, max_length=5, null=True)),
                ('BloodType', models.CharField(default='N/D', max_length=3)),
                ('Gender', models.CharField(default='Male', max_length=8)),
                ('CivilStatus', models.CharField(default='N/A', max_length=10)),
                ('Address', models.CharField(default='N/D', max_length=200)),
                ('HomeAddress', models.CharField(default=None, max_length=200, null=True)),
                ('PhoneNo', models.CharField(default=None, max_length=12, null=True)),
                ('Email', models.CharField(default=None, max_length=50, null=True)),
                ('Position', models.CharField(max_length=50)),
                ('Department', models.CharField(blank=True, default='N/A', max_length=50, null=True)),
                ('EmployementDate', models.DateField(default=None, null=True)),
                ('EmploymentStatus', models.CharField(default='Regular', max_length=15)),
                ('EmployeeStatus', models.CharField(default=None, max_length=15, null=True)),
                ('EmpImage', models.CharField(blank=True, default='N/A', max_length=50, null=True)),
                ('BranchCode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HromApp.branches')),
            ],
        ),
    ]
