# Generated by Django 4.2.7 on 2025-03-04 01:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HromApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rejectedapplication',
            old_name='RejectedDAte',
            new_name='RejectedDate',
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='DateApplied',
            field=models.DateField(default=datetime.date(2025, 3, 4), null=True),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='JobDate',
            field=models.DateField(default=datetime.date(2025, 3, 4), null=True),
        ),
        migrations.AlterField(
            model_name='useracc',
            name='AccDate',
            field=models.DateField(default=datetime.date(2025, 3, 4), null=True),
        ),
    ]
