# Generated by Django 4.2.7 on 2025-03-04 01:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HromApp', '0002_rename_rejecteddate_rejectedapplication_rejecteddate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inprogressapplication',
            name='AssesmentDAte',
        ),
        migrations.AlterField(
            model_name='useracc',
            name='AccDate',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='useracc',
            name='Username',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='inprogressapplication',
            name='AssesmentDate',
            field=models.DateField(default=None, null=True),
        ),
    ]
