# Generated by Django 4.2.7 on 2025-03-04 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HromApp', '0003_remove_inprogressapplication_assesmentdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblist',
            name='JobBranch',
        ),
        migrations.AddField(
            model_name='joblist',
            name='BranchCode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HromApp.branches'),
        ),
    ]
