# Generated by Django 4.2.7 on 2025-03-04 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HromApp', '0004_remove_joblist_jobbranch_joblist_branchcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useracc',
            name='UserCode',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='useracc',
            name='Username',
            field=models.CharField(max_length=50),
        ),
    ]
