# Generated by Django 4.2.7 on 2025-03-06 05:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HromApp', '0005_alter_useracc_usercode_alter_useracc_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='useracc',
            name='AboutUser',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='DateApplied',
            field=models.DateField(default=datetime.date(2025, 3, 6), null=True),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='JobDate',
            field=models.DateField(default=datetime.date(2025, 3, 6), null=True),
        ),
        migrations.AlterField(
            model_name='useracc',
            name='Password',
            field=models.CharField(max_length=50),
        ),
    ]
