# Generated by Django 4.2.7 on 2025-03-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HromApp', '0006_useracc_aboutuser_alter_jobapplication_dateapplied_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useracc',
            name='AboutUser',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
