# Generated by Django 4.2.7 on 2025-03-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HromApp', '0007_alter_useracc_aboutuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='useracc',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
