# Generated by Django 4.2.7 on 2025-03-10 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HromApp', '0009_remove_useracc_aboutuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useracc',
            name='AboutUser',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='UserDetails',
        ),
    ]
