# Generated by Django 4.2.7 on 2025-03-10 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HromApp', '0010_useracc_aboutuser_delete_userdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AboutUser', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('UserAddress', models.CharField(default='N/D', max_length=150)),
                ('UserSkills', models.JSONField()),
                ('UserResume', models.CharField(default='N/D', max_length=150)),
                ('ApplicantCode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='HromApp.useracc')),
            ],
        ),
    ]
