# Generated by Django 4.2.7 on 2025-03-10 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HromApp', '0011_userdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='UserSkills',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
