# Generated by Django 4.2.7 on 2025-03-10 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HromApp', '0012_alter_userdetails_userskills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useracc',
            name='AboutUser',
        ),
        migrations.AlterField(
            model_name='joblist',
            name='JobBenefits',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='JobQual',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='JobTypes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
