# Generated by Django 4.2.7 on 2025-03-11 01:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HromApp', '0013_remove_useracc_aboutuser_alter_joblist_jobbenefits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='DateApplied',
            field=models.DateField(default=datetime.date(2025, 3, 11), null=True),
        ),
        migrations.AlterField(
            model_name='joblist',
            name='JobDate',
            field=models.DateField(default=datetime.date(2025, 3, 11), null=True),
        ),
    ]
