# Generated by Django 4.2.7 on 2025-03-11 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HromApp', '0014_alter_jobapplication_dateapplied_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblist',
            name='JobDate',
            field=models.DateTimeField(default=datetime.datetime.now, null=True),
        ),
    ]
