# Generated by Django 4.2.7 on 2025-03-19 07:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HromApp', '0015_alter_joblist_jobdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joblist',
            old_name='JobLoc',
            new_name='JobBrgy',
        ),
        migrations.AddField(
            model_name='joblist',
            name='JobCity',
            field=models.CharField(blank=True, default='N/D', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='joblist',
            name='JobProvince',
            field=models.CharField(blank=True, default='N/D', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='DateApplied',
            field=models.DateField(default=datetime.date(2025, 3, 19), null=True),
        ),
    ]
