# Generated by Django 4.2.7 on 2025-03-20 05:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HromApp', '0016_rename_jobloc_joblist_jobbrgy_joblist_jobcity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='ExpectSalary',
            new_name='ExpectedSalary',
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='DateApplied',
            field=models.DateField(default=datetime.date(2025, 3, 20), null=True),
        ),
    ]
